version: '3.8'

services:
  api:
    build:
      context: ./backend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules # Anonymous volume to protect container modules
    env_file:
      - .env
      - .env.test
    environment:
      - DATABASE_URL=mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/${MONGO_DB}?authSource=admin
    depends_on:
      - mongo
      
  # The MongoDB Database
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # Exposed so you can use Compass/Studio3T locally
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db # PERSISTENCE: Keeps your data safe

volumes:
  mongo-data: