
services:
  api:
    build:
      context: ./backend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules # Anonymous volume to protect container modules
    env_file:
      - .env
      - .env.test
    depends_on:
      - mongo-dev
      - mongo-test
      
  # The MongoDB Database
  # 1. Development Database (Persists your work)
  mongo-dev:
    image: mongo:latest
    container_name: quik-mongo-dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - dev-data:/data/db

  # 2. Testing Database (Wiped constantly by Vitest)
  mongo-test:
    image: mongo:latest
    container_name: quik-mongo-test
    ports:
      - "27018:27017" # Map internal 27017 to host 27018 to avoid conflict
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - test-data:/data/db

volumes:
  dev-data:
  test-data: